{{- if .Values.internal.certmanager.enabled }}
{{- $cn := "NeuVector" }}
{{- $cert := genSelfSignedCert $cn nil (list $cn "neuvector.internal" "NeuVector") (.Values.defaultValidityPeriod | int) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.internal.certmanager.secretname }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.key: {{ include "neuvector.secrets.lookup" (dict "namespace" .Release.Namespace "secret" .Values.internal.certmanager.secretname "key" "tls.key" "defaultValue" $cert.Key) }}

  tls.crt: {{ include "neuvector.secrets.lookup" (dict "namespace" .Release.Namespace "secret" .Values.internal.certmanager.secretname "key" "tls.crt" "defaultValue" $cert.Cert) }}
{{- end -}}
