{{- if .Values.crdwebhooksvc.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: neuvector-svc-crd-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 443
      targetPort: 30443
      protocol: TCP
      name: crd-webhook
  type: {{ .Values.crdwebhook.type }}
  selector:
    app: neuvector-controller-pod
{{- end }}
