{{- if .Values.crdwebhook.enabled -}}
{{- $oc4 := and .Values.openshift (semverCompare ">=1.12-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) -}}
{{- $oc3 := and .Values.openshift (not $oc4) (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) -}}
{{- if (semverCompare ">=1.19-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: apiextensions.k8s.io/v1
{{- else }}
apiVersion: apiextensions.k8s.io/v1beta1
{{- end }}
kind: CustomResourceDefinition
metadata:
  name: nvsecurityrules.neuvector.com
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: neuvector.com
  names:
    kind: NvSecurityRule
    listKind: NvSecurityRuleList
    plural: nvsecurityrules
    singular: nvsecurityrule
  scope: Namespaced
{{- if (semverCompare "<1.19-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
  version: v1
{{- end }}
  versions:
  - name: v1
    served: true
    storage: true
{{- if (semverCompare ">=1.19-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              egress:
                items:
                  properties:
                    action:
                      type: string
                    applications:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                    ports:
                      type: string
                    priority:
                      type: integer
                    selector:
                      properties:
                        criteria:
                          items:
                            properties:
                              key:
                                type: string
                              op:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        name:
                          type: string
                        original_name:
                          type: string
                      type: object
                  type: object
                type: array
              file:
                items:
                  properties:
                    app:
                      items:
                        type: string
                      type: array
                    behavior:
                      type: string
                    filter:
                      type: string
                    recursive:
                      type: boolean
                  type: object
                type: array
              ingress:
                items:
                  properties:
                    action:
                      type: string
                    applications:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                    ports:
                      type: string
                    priority:
                      type: integer
                    selector:
                      properties:
                        criteria:
                          items:
                            properties:
                              key:
                                type: string
                              op:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        name:
                          type: string
                        original_name:
                          type: string
                      type: object
                  type: object
                type: array
              process:
                items:
                  properties:
                    action:
                      type: string
                    name:
                      type: string
                    path:
                      type: string
                  type: object
                type: array
              target:
                properties:
                  policymode:
                    type: string
                  selector:
                    properties:
                      criteria:
                        items:
                          properties:
                            key:
                              type: string
                            op:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                      name:
                        type: string
                      original_name:
                        type: string
                    type: object
                type: object
            required:
            - target
            type: object
        type: object
{{- end }}
---
{{- if (semverCompare ">=1.19-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: apiextensions.k8s.io/v1
{{- else }}
apiVersion: apiextensions.k8s.io/v1beta1
{{- end }}
kind: CustomResourceDefinition
metadata:
  name: nvclustersecurityrules.neuvector.com
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: neuvector.com
  names:
    kind: NvClusterSecurityRule
    listKind: NvClusterSecurityRuleList
    plural: nvclustersecurityrules
    singular: nvclustersecurityrule
  scope: Cluster
{{- if (semverCompare "<1.19-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
  version: v1
{{- end }}
  versions:
  - name: v1
    served: true
    storage: true
{{- if (semverCompare ">=1.19-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              egress:
                items:
                  properties:
                    action:
                      type: string
                    applications:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                    ports:
                      type: string
                    priority:
                      type: integer
                    selector:
                      properties:
                        criteria:
                          items:
                            properties:
                              key:
                                type: string
                              op:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        name:
                          type: string
                        original_name:
                          type: string
                      type: object
                  type: object
                type: array
              file:
                items:
                  properties:
                    app:
                      items:
                        type: string
                      type: array
                    behavior:
                      type: string
                    filter:
                      type: string
                    recursive:
                      type: boolean
                  type: object
                type: array
              ingress:
                items:
                  properties:
                    action:
                      type: string
                    applications:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                    ports:
                      type: string
                    priority:
                      type: integer
                    selector:
                      properties:
                        criteria:
                          items:
                            properties:
                              key:
                                type: string
                              op:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        name:
                          type: string
                        original_name:
                          type: string
                      type: object
                  type: object
                type: array
              process:
                items:
                  properties:
                    action:
                      type: string
                    name:
                      type: string
                    path:
                      type: string
                  type: object
                type: array
              target:
                properties:
                  policymode:
                    type: string
                  selector:
                    properties:
                      criteria:
                        items:
                          properties:
                            key:
                              type: string
                            op:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                      name:
                        type: string
                      original_name:
                        type: string
                    type: object
                type: object
            required:
            - target
            type: object
        type: object
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: neuvector-svc-crd-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 443
      targetPort: 30443
      protocol: TCP
      name: crd-webhook
  type: {{ .Values.crdwebhook.type }}
  selector:
    app: neuvector-controller-pod
---
# ClusterRole for NeuVector to operate CRD
{{- if $oc3 }}
apiVersion: authorization.openshift.io/v1
{{- else if (semverCompare ">=1.8-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: v1
{{- end }}
kind: ClusterRole
metadata:
  name: neuvector-binding-customresourcedefinition
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - watch
  - create
  - get
---
# ClusterRoleBinding for NeuVector to operate CRD
{{- if $oc3 }}
apiVersion: authorization.openshift.io/v1
{{- else if (semverCompare ">=1.8-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: v1
{{- end }}
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-customresourcedefinition
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
{{- if not $oc3 }}
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
{{- end }}
  name: neuvector-binding-customresourcedefinition
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Release.Namespace }}
{{- if $oc3 }}
userNames:
- system:serviceaccount:{{ .Release.Namespace }}:{{ .Values.serviceAccount }}
{{- end }}
---
# ClusterRole for NeuVector to manager user-created CRD rules
{{- if $oc3 }}
apiVersion: authorization.openshift.io/v1
{{- else if (semverCompare ">=1.8-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: v1
{{- end }}
kind: ClusterRole
metadata:
  name: neuvector-binding-nvsecurityrules
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - neuvector.com
  resources:
  - nvsecurityrules
  - nvclustersecurityrules
  verbs:
  - list
  - delete
---
# ClusterRoleBinding for NeuVector to manager user-created CRD rules
{{- if $oc3 }}
apiVersion: authorization.openshift.io/v1
{{- else if (semverCompare ">=1.8-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: v1
{{- end }}
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvsecurityrules
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
{{- if not $oc3 }}
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
{{- end }}
  name: neuvector-binding-nvsecurityrules
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Release.Namespace }}
{{- if $oc3 }}
userNames:
- system:serviceaccount:{{ .Release.Namespace }}:{{ .Values.serviceAccount }}
{{- end }}
{{- end }}
