{{- if .Values.aws-billing.enabled }}
{{- if not .Values.openshift}}
{{- if ne .Values.aws-billing.serviceAccount "default"}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.aws-billing.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountNumber }}:role/{{ .Values.aws.roleName }}
{{- end }}
{{- end }}
{{- end }}
