{{- if .Values.openshift -}}
{{- if (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: route.openshift.io/v1
{{- else }}
apiVersion: v1
{{- end }}
kind: Route
metadata:
  name: neuvector-route-webui
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  to:
    kind: Service
    name: neuvector-service-webui
  port:
    targetPort: manager
  tls:
    termination: passthrough
{{ if or ( eq .Values.controller.apisvc.type "ClusterIP") (eq .Values.controller.apisvc.type "NodePort") -}}
---
{{- if (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: route.openshift.io/v1
{{- else }}
apiVersion: v1
{{- end }}
kind: Route
metadata:
  name: neuvector-route-api
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  to:
    kind: Service
    name: neuvector-svc-controller-api
  port:
    targetPort: controller-api
  tls:
    termination: passthrough
{{- end }}
{{ if or ( eq .Values.controller.federation.mastersvc.type "ClusterIP") (eq .Values.controller.federation.mastersvc.type "NodePort") -}}
---
{{- if (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: route.openshift.io/v1
{{- else }}
apiVersion: v1
{{- end }}
kind: Route
metadata:
  name: neuvector-route-fed-master
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  to:
    kind: Service
    name: neuvector-svc-controller-fed-master
  port:
    targetPort: fed
  tls:
    termination: passthrough
{{- end }}
{{ if or ( eq .Values.controller.federation.managedsvc.type "ClusterIP") (eq .Values.controller.federation.managedsvc.type "NodePort") -}}
---
{{- if (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: route.openshift.io/v1
{{- else }}
apiVersion: v1
{{- end }}
kind: Route
metadata:
  name: neuvector-route-fed-managed
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  to:
    kind: Service
    name: neuvector-svc-controller-fed-managed
  port:
    targetPort: fed
  tls:
    termination: passthrough
{{- end }}
{{- end }}
