apiVersion: v1
appVersion: 5.1.1
description: Cloud Service Provider Marketplace Adapter for Neuvector. Monitors Neuvector entitlements against usage.
name: neuvector-csp-adapter
version: 1.0.0
home: https://neuvector.com
icon: https://avatars2.githubusercontent.com/u/19367275?s=200&v=4
maintainers:
  - name: becitsthere
    email: support@neuvector.com
engine: gotpl
