{{- $oc4 := and .Values.openshift (semverCompare ">=1.12-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) -}}
{{- $oc3 := and .Values.openshift (not $oc4) (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) -}}
{{- if (semverCompare ">=1.19-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: apiextensions.k8s.io/v1
{{- else }}
apiVersion: apiextensions.k8s.io/v1beta1
{{- end }}
kind: CustomResourceDefinition
metadata:
  name: settings.neuvector.com
  labels:
    chart: {{ template "neuvector-csp-adapter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: neuvector.com
  names:
    kind: Setting
    listKind: SettingList
    plural: settings
    singular: setting
  scope: Cluster
{{- if (semverCompare "<1.19-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
  version: v1
{{- end }}
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          customized:
            type: boolean
          value:
            nullable: true
            type: string
          default:
            nullable: true
            type: string
          source:
            nullable: true
            type: string
        type: object
    served: true
    storage: true
---
{{- $oc4 := and .Values.openshift (semverCompare ">=1.12-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) -}}
{{- $oc3 := and .Values.openshift (not $oc4) (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) -}}
{{- if (semverCompare ">=1.19-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: apiextensions.k8s.io/v1
{{- else }}
apiVersion: apiextensions.k8s.io/v1beta1
{{- end }}
kind: CustomResourceDefinition
metadata:
  name: neuvectorusernotifications.neuvector.com
  labels:
    chart: {{ template "neuvector-csp-adapter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: neuvector.com
  names:
    kind: NeuvectorUserNotification
    listKind: NeuvectorUserNotificationList
    plural: neuvectorusernotifications
    singular: neuvectorusernotification
  scope: Cluster
{{- if (semverCompare "<1.19-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
  version: v1
{{- end }}
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          componentName:
            type: string
          message:
            type: string
        type: object
    served: true
    storage: true
