{{- $oc4 := and .Values.openshift (semverCompare ">=1.12-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) -}}
{{- $oc3 := and .Values.openshift (not $oc4) (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) -}}
{{- if (semverCompare ">=1.19-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: apiextensions.k8s.io/v1
{{- else }}
apiVersion: apiextensions.k8s.io/v1beta1
{{- end }}
kind: CustomResourceDefinition
metadata:
  name: neuvectorusagerecords.neuvector.com
  labels:
    chart: {{ template "neuvector-csp-adapter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: neuvector.com
  names:
    kind: NeuvectorUsageRecord
    listKind: NeuvectorUsageRecordList
    plural: neuvectorusagerecords
    singular: neuvectorusagerecord
  scope: Cluster
{{- if (semverCompare "<1.19-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
  version: v1
{{- end }}
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          usage:
            type: integer
          extensions:
            type: string
          version:
            type: string
          timestamp:
            type: string
        required:
          - usage
          - version
          - timestamp
        type: object
    served: true
    storage: true
